# Lab 1 Part II: UCI-HAR 1D CNN

## Imports

In [2]:
from pathlib import Path
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Input, Conv1D, MaxPool1D, Flatten, Dense, Activation
from keras.utils.data_utils import get_file
from keras.utils.np_utils import to_categorical

## Load and format UCI-HAR dataset (raw data)

In [3]:
dataset_path = get_file(None, "https://archive.ics.uci.edu/ml/machine-learning-databases/00240/UCI%20HAR%20Dataset.zip", extract=True, file_hash="53e099237392e0b9602f8c38f578bd8f") # Download, cache and extract UCI-HAR
dataset_dir = Path(dataset_path).parent

def load_set(dataset_dir, part: str): # Load separate sensor signals and combine them into a single array, load labels separately
    data = np.hstack([np.loadtxt(dataset_dir/'UCI HAR Dataset'/part/'Inertial Signals'/f'{sensor}_{axis}_{part}.txt')
                for sensor in ('body_acc', 'body_gyro', 'total_acc')
                    for axis in ('x', 'y', 'z')]).reshape((-1, 128, 9))
    labels = to_categorical(np.loadtxt(dataset_dir/'UCI HAR Dataset'/part/f'y_{part}.txt') - 1)
    return data, labels

x_train, y_train = load_set(dataset_dir, 'train')
x_test, y_test = load_set(dataset_dir, 'test')

## Export complete test dataset (2947 vectors)

In [4]:
np.savetxt('x_test_uci-har.csv', x_test.reshape((x_test.shape[0], -1)), delimiter=',', fmt='%s')
np.savetxt('y_test_uci-har.csv', y_test, delimiter=',', fmt='%s')

## Export small test dataset (250 vectors)

In [5]:
x_test_250 = x_test[0:250]
y_test_250 = y_test[0:250]
np.savetxt('x_test_uci-har_250.csv', x_test_250.reshape((x_test_250.shape[0], -1)), delimiter=',', fmt='%s')
np.savetxt('y_test_uci-har_250.csv', y_test_250, delimiter=',', fmt='%s')

## Build model

In [15]:
# model = Sequential()
# model.add(Input(shape=(128, 9)))
# model.add(Conv1D(filters=2, kernel_size=3, activation='relu'))
# model.add(Flatten())
# model.add(Dense(units=6))
# model.add(Activation('softmax')) # SoftMax activation needs to be separate from Dense to remove it later on
# # EXPLORE Learning Rate
# opt = tf.keras.optimizers.Adam(learning_rate=10e-3)
# model.summary()
# model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['categorical_accuracy'])


model = Sequential()
model.add(Input(shape=(128, 9))) # 128 data points form sensors | 9 time steps
model.add(Conv1D(filters=28, kernel_size=65, activation='relu'))
model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(MaxPool1D(pool_size=2))
# model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(units=6))
model.add(Activation('softmax')) # SoftMax activation needs to be separate from Dense to remove it later on

# EXPLORE Learning Rate
opt = tf.keras.optimizers.Adam(lr=5e-3)
model.summary()
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['categorical_accuracy'])

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_3 (Conv1D)           (None, 126, 32)           896       
                                                                 
 conv1d_4 (Conv1D)           (None, 124, 64)           6208      
                                                                 
 max_pooling1d_1 (MaxPooling  (None, 62, 64)           0         
 1D)                                                             
                                                                 
 flatten_2 (Flatten)         (None, 3968)              0         
                                                                 
 dense_2 (Dense)             (None, 6)                 23814     
                                                                 
 activation_2 (Activation)   (None, 6)                 0         
                                                      

## Train model

In [19]:
hist1 = model.fit(x_train, y_train, epochs=3, validation_data=(x_test, y_test))
hist2 = model.fit(x_train, y_train, epochs=3, validation_data=(x_test, y_test))
hist3 = model.fit(x_train, y_train, epochs=3, validation_data=(x_test, y_test))

Epoch 1/3
230/230 [==============================] - 3s 14ms/step - loss: 0.0736 - categorical_accuracy: 0.9699 - val_loss: 0.2450 - val_categorical_accuracy: 0.9372
Epoch 2/3
230/230 [==============================] - 3s 14ms/step - loss: 0.0556 - categorical_accuracy: 0.9785 - val_loss: 0.2737 - val_categorical_accuracy: 0.9393
Epoch 3/3
230/230 [==============================] - 3s 14ms/step - loss: 0.0639 - categorical_accuracy: 0.9762 - val_loss: 0.2184 - val_categorical_accuracy: 0.9535
Epoch 1/3
230/230 [==============================] - 3s 14ms/step - loss: 0.0520 - categorical_accuracy: 0.9825 - val_loss: 0.2396 - val_categorical_accuracy: 0.9539
Epoch 2/3
230/230 [==============================] - 3s 15ms/step - loss: 0.0382 - categorical_accuracy: 0.9860 - val_loss: 0.4072 - val_categorical_accuracy: 0.9335
Epoch 3/3
230/230 [==============================] - 3s 14ms/step - loss: 0.0364 - categorical_accuracy: 0.9856 - val_loss: 0.3087 - val_categorical_accuracy: 0.9430
Epoc

In [25]:
hists = [hist1, hist2, hist3]
accuracies = []
stds = []

i = 1
for hist in hists:

    print("Train {0}:".format(i))

    print(hist.history["categorical_accuracy"])
    print(hist.history["loss"])

    accuracies.append(hist.history["categorical_accuracy"])
    stds.append(hist.history["loss"])

    i += 1

print(np.mean(accuracies))
print(np.mean(stds))


Train 1:
Train 1 :
[0.9699401259422302, 0.978509247303009, 0.9761969447135925]
[0.07358816266059875, 0.05560464784502983, 0.06385743618011475]
Train 2:
Train 2 :
[0.9824537038803101, 0.9859901666641235, 0.9855821132659912]
[0.05195469409227371, 0.03816013038158417, 0.0364258736371994]
Train 3:
Train 3 :
[0.9888465404510498, 0.986126184463501, 0.9908868074417114]
[0.037058569490909576, 0.06052679568529129, 0.026058565825223923]
0.9827257593472799
0.04924831953313616


## Evaluate model on complete test dataset

In [17]:
model.evaluate(x_test, y_test, verbose=2)
pred_test = model.predict(x_test)
print(tf.math.confusion_matrix(y_test.argmax(axis=1), pred_test.argmax(axis=1)))

93/93 - 1s - loss: 0.3261 - categorical_accuracy: 0.9223 - 741ms/epoch - 8ms/step
67/93 [====================>.........] - ETA: 0s

2023-03-11 17:20:22.077618: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


93/93 [==============================] - 0s 3ms/step
tf.Tensor(
[[489   5   1   0   1   0]
 [ 20 449   2   0   0   0]
 [ 44  34 342   0   0   0]
 [  1   3   0 380 107   0]
 [  1   1   0   9 521   0]
 [  0   0   0   0   0 537]], shape=(6, 6), dtype=int32)


## Evaluate model on small test dataset

In [18]:
model.evaluate(x_test_250, y_test_250, verbose=2)
pred_test_250 = model.predict(x_test_250)
print(tf.math.confusion_matrix(y_test_250.argmax(axis=1), pred_test_250.argmax(axis=1)))

8/8 - 0s - loss: 0.6598 - categorical_accuracy: 0.8000 - 91ms/epoch - 11ms/step
8/8 [==============================] - 0s 5ms/step
tf.Tensor(
[[53  0  0  0  0  0]
 [ 0 25  0  0  0  0]
 [ 1 16  7  0  0  0]
 [ 0  0  0 13 33  0]
 [ 0  0  0  0 54  0]
 [ 0  0  0  0  0 48]], shape=(6, 6), dtype=int32)


## Save trained model

In [10]:
model.save('lab1_part2_uci-har.h5')